CREATE DATABASE IF NOT EXISTS session_exercise;
Use session_exercise;
CREATE TABLE IF NOT EXISTS users  (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE KEY,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  born_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);