CREATE DATABASE IF NOT EXISTS shoporm COLLATE 'utf8_general_ci';
USE shoporm;

CREATE TABLE IF NOT EXISTS users(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE KEY,
password VARCHAR(255) NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NULL,
born_on DATETIME DEFAULT CURRENT_TIMESTAMP);
